# -*- coding: utf-8 -*-
{
    'name': 'MEGASTOCK Inventory System',
    'version': '16.0.3.0.0',
    'category': 'Inventory',
    'summary': 'Gestión de materias primas e inventarios para MEGASTOCK',
    'description': "",
    'author': 'MEGASTOCK',
    'website': 'https://megastock.com',
    'depends': [
        'base',
        'stock',
        'purchase',
        'purchase_stock',
        'mrp',
        'product',
        'product_expiry',
        'megastock_base',
        'megastock_products',
    ],
    'data': [
        'data/raw_materials_data.xml',
        'data/stock_locations_data.xml',
        'data/suppliers_data.xml',
        'data/inventory_rules_data.xml',
        'views/stock_location_views.xml',
        'views/stock_quant_views.xml',
        'views/purchase_order_views.xml',
        'views/stock_picking_views.xml',
        'wizard/material_transfer_wizard_views.xml',
        'wizard/stock_alert_wizard_views.xml',
        'reports/material_consumption_report.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}